# Generated by Django 3.2.9 on 2021-12-26 12:22

import deployment.models
from django.db import migrations, models
import django.utils.timezone
import semantic_version.django_fields


class Migration(migrations.Migration):

    replaces = [('deployment', '0001_initial'), ('deployment', '0002_auto_20211219_0837'), ('deployment', '0003_alter_deployment_version'), ('deployment', '0004_alter_deployment_options'), ('deployment', '0005_alter_deployment_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_date', models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Deployment date')),
                ('version', semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False)),
                ('hash', models.CharField(default=deployment.models.branch_hash, max_length=40, verbose_name='Hexadecimal hash')),
                ('commit_date', models.DateTimeField(default=deployment.models.branch_date, verbose_name='Commit date')),
                ('branch', models.CharField(default='master', max_length=2048, verbose_name='Branch')),
                ('git', models.URLField(default='https://github.com/jw/zink.git', verbose_name='Repository')),
            ],
            options={
                'get_latest_by': ['deployment_date'],
                'ordering': ['deployment_date'],
            },
        ),
    ]
