# Generated by Django 3.2.9 on 2021-12-11 20:31

from django.db import migrations, models
import semantic_version.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_date', models.DateTimeField(verbose_name='Deployment date')),
                ('version', semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False)),
                ('hash', models.CharField(max_length=40, verbose_name='Hexadecimal hash')),
                ('commit_date', models.DateTimeField(verbose_name='Deployment date')),
                ('branch', models.CharField(max_length=2048, verbose_name='Branch')),
            ],
        ),
    ]
