# Generated by Django 3.2.9 on 2021-12-19 08:37

import deployment.models
from django.db import migrations, models
import django.utils.timezone
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='git',
            field=models.URLField(default='https://github.com/jw/zink.git', verbose_name='Repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deployment',
            name='branch',
            field=models.CharField(default='master', max_length=2048, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='commit_date',
            field=models.DateTimeField(default=deployment.models.branch_date, verbose_name='Commit date'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True, verbose_name='Deployment date'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='hash',
            field=models.CharField(default=deployment.models.branch_hash, max_length=40, verbose_name='Hexadecimal hash'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False, unique=True),
        ),
    ]
