# Generated by Django 3.2.9 on 2021-12-19 08:38

from django.db import migrations
import semantic_version.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0002_auto_20211219_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='version',
            field=semantic_version.django_fields.VersionField(coerce=False, max_length=200, partial=False),
        ),
    ]
