  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=zink
        - POSTGRES_USER=zink
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    web:
      build: .
      command: ./entrypoint.sh
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
