[tool.poetry]
name = "zink"
version = "3.0.0"
description = "ElevenBits website."
authors = ["Jan Willems"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.3"
django-debug-toolbar = "^2.2"
django-environ = "^0.4.5"
dj-database-url = "^0.5.0"
sentry-sdk = "^0.14.1"
django-widget-tweaks = "^1.4.5"
django-extensions = "^2.2.8"
whitenoise = "^5.0.1"
django-sitetree = "^1.14.0"
psycopg2-binary = "^2.8.4"
mistune = "^0.8.4"
pygments = "^2.5.2"
Pillow = "^7.0.0"

[tool.poetry.dev-dependencies]
pytest = "flake8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
