[tool.poetry]
name = "zink"
version = "4.0.0"
description = "ElevenBits website"
authors = ["Jan Willems <jw@elevenbts.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.8"
gunicorn = "^20.0.4"
psycopg2 = "^2.8.5"
environs = "^8.0.0"
dj-database-url = "^0.5.0"
whitenoise = "^5.1.0"
django_compressor = "^2.4"
mistune = "^0.8.4"
pygments = "^2.7.4"
django-treenode = "^0.14.2"
Whoosh = "^2.7.4"
django-haystack = "3.0b2"
beautifulsoup4 = "^4.9.1"
lxml = "^4.5.2"
Pillow = "^7.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
black = "^19.10b0"
pre-commit = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
