[tool]
[tool.poetry]
name = "zink"
version = "0.1.1"
description = "The elevenbits.com website."
authors = ["Jan Willems <jw@elevenbits.com>"]

[tool.poetry.dependencies]
python = "^3.10.0"
argon2-cffi = "==21.3.0"
collectfast = "==2.2.0"
django = "^4.1.0"
django-allauth = "^0.51.0"
django-anymail = {version = "^8.6", extras = ["mailgun"]}
django-crispy-forms = "^1.14.0"
django-environ = "^0.9.0"
django-model-utils = "^4.2.0"
django-redis = "^5.2.0"
django-storages = {version = "^1.13.1", extras = ["boto3"]}
gunicorn = "^20.1.0"
hiredis = "^2.0.0"
pillow = "^9.2.0"
psycopg = "^3.1.1"
python-slugify = "^6.1.2"
pytz = "^2022.2.1"
redis = "^4.3.4"
sentry-sdk = "^1.9.8"
whitenoise = "^6.2.0"
Werkzeug = "^2.2.2"
environs = "^9.3.2"
dj-database-url = "^1.0.0"
mistune = "^2.0.4"
beautifulsoup4 = "^4.9.3"
django-treenode = "^0.18.2"
Whoosh = "^2.7.4"
django-compressor = "^4.1"
django-haystack = "^3.2.1"
semantic-version = "^2.8.5"
GitPython = "^3.1.24"
psycopg2 = "^2.9.3"

[tool.poetry.group.dev.dependencies]
mypy = "^0.971"
django-stubs = "^1.12.0"
pytest = "^7.1.3"
pytest-sugar = "^0.9.4"
Sphinx = "^5.1.1"
flake8 = "^5.0.4"
flake8-isort = "^4.0.0"
coverage = "^6.4.4"
black = "^22.8.0"
pylint-django = "^2.4.2"
pre-commit = "^2.11.1"
django-debug-toolbar = "^3.2"
django-extensions = "^3.1.1"
pytest-django = "^4.1.0"
factory-boy = "^3.2.0"
ipython = "^8.5.0"
httpie = "^3.2.1"
