[tool]
[tool.poetry]
name = "zink"
version = "0.1.0"
description = ""
authors = ["Jan Willems <jw@elevenbits.com>"]

[tool.poetry.dependencies]
python = "==3.9.9"
argon2-cffi = "==20.1.0"
collectfast = "==2.2.0"
django = "==3.2.9"
django-allauth = "==0.44.0"
django-anymail = {version = "==8.2", extras = ["mailgun"]}
django-crispy-forms = "==1.11.2"
django-environ = "==0.4.5"
django-model-utils = "==4.1.1"
django-redis = "==4.12.1"
django-storages = {version = "==1.11.1", extras = ["boto3"]}
gunicorn = "==20.0.4"
hiredis = "==1.1.0"
pillow = "==8.4.0"
psycopg2 = "==2.8.6"
python-slugify = "==4.0.1"
pytz = "==2021.1"
redis = "==3.5.3"
sentry-sdk = "==0.20.3"
whitenoise = "^5.2.0"
Werkzeug = "^1.0.1"
environs = "^9.3.2"
dj-database-url = "^0.5.0"
mistune = "^0.8.4"
beautifulsoup4 = "^4.9.3"
django-treenode = "^0.15.0"
Whoosh = "^2.7.4"
django-compressor = "^2.4.1"
django-haystack = "^3.1.1"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
django-stubs = "^1.7.0"
pytest = "^6.2.3"
pytest-sugar = "^0.9.4"
Sphinx = "^4.0.0"
sphinx-autobuild = "^2021.3.14"
flake8 = "^3.9.0"
flake8-isort = "^4.0.0"
coverage = "^5.5"
black = "^20.8b1"
pylint-django = "^2.4.2"
pre-commit = "^2.11.1"
django-debug-toolbar = "^3.2"
django-extensions = "^3.1.1"
django-coverage-plugin = "^1.8.0"
pytest-django = "^4.1.0"
factory-boy = "^3.2.0"
httpie = "^2.4.0"
ipython = "^7.30.1"
