[tool.poetry]
name = "zink"
version = "4.0.0"
description = ""
authors = ["Jan Willems <jan.willems@elevenbits.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
