[tool.poetry]
name = "zink"
version = "3.0.0"
description = "ElevenBits website."
authors = ["Jan Willems <jw@elevenbits.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
beautifulsoup4 = "^4.8.2"
django = "^3.0.3"
django-debug-toolbar = "^2.2"
django-environ = "^0.4.5"
django-extensions = "^2.2.8"
django-heroku = "^0.3.1"
django-pipeline = "^1.7.0"
django-widget-tweaks = "^1.4.5"
dj-database-url = "^0.5.0"
gunicorn = "^20.0.4"
jsonfield = "^3.0.0"
mistune = "^0.8.4"
Pillow = "^7.0.0"
psycopg2-binary = "^2.8.4"
pygments = "^2.5.2"
sentry-sdk = "^0.14.1"
twitter = "^1.18.0"
whitenoise = "^5.0.1"
whoosh = "^2.7.4"
django-haystack = "3.0b1"
django-treenode = "^0.14.2"

[tool.poetry.dev-dependencies]
pytest = "flake8"
werkzeug = "^1.0.0"
flake8 = "^3.7.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
