databases:
  - name: zink
    databaseName: zink
    user: zink

services:
  - type: web
    name: zink
    env: python
    region: frankfurt
    plan: starter
    repo: https://github.com/jw/zink.git
    branch: master
    buildCommand: "./build.sh"
    startCommand: "gunicorn elevenbits.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zink
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.1
      - key: NODE_VERSION
        value: 18.15.0
      - key: WEB_CONCURRENCY
        value: 4
