databases:
  - name: zink
    databaseName: zink
    user: zink

services:
  - type: web
    name: zink
    env: python
    region: frankfurt
    rootDir: elevenbits
    buildCommand: "./bin/build.sh"
    startCommand: "gunicorn main.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zink
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
