# Generated by Django 3.0.7 on 2020-07-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='The tag of this deployment.', max_length=255, verbose_name='tag')),
                ('version', models.CharField(max_length=255, verbose_name='version')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('deployer', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Deployments',
                'ordering': ['timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
    ]
