# Generated by Django 2.0 on 2018-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('vat', models.CharField(max_length=16)),
                ('account', models.CharField(max_length=32)),
            ],
        ),
    ]
