# Generated by Django 2.0 on 2018-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', max_length=255, upload_to='tmp/', width_field='width'),
        ),
    ]
