# Generated by Django 2.0 on 2018-02-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', max_length=255, upload_to='tmp', width_field='width')),
                ('description', models.TextField(help_text='Description of the image.')),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(help_text='The content of this entry.'),
        ),
        migrations.AddField(
            model_name='entry',
            name='images',
            field=models.ManyToManyField(to='blog.Image'),
        ),
    ]
