# Generated by Django 2.0 on 2018-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180304_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='images',
            field=models.ManyToManyField(blank=True, to='blog.Image'),
        ),
    ]
