# Generated by Django 2.0.2 on 2018-03-19 22:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180304_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Title of the text.')),
                ('pages', models.IntegerField()),
                ('current_page', models.IntegerField()),
                ('ranking', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='topics',
            field=models.ManyToManyField(blank=True, to='blog.Topic'),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Type'),
        ),
    ]
