# Generated by Django 2.0.2 on 2018-03-19 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180319_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author',
            field=models.TextField(default='Jesper Roine', help_text='Authors of the text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='ranking',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
