# Generated by Django 3.0.3 on 2020-03-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200323_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
