# Generated by Django 2.0.2 on 2018-03-19 23:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180319_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 23, 3, 26, 707159), help_text='Date and time when this text came into my hands.', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='text',
            name='read',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 23, 3, 26, 707181), help_text='Date and time when this text was read.', verbose_name='created'),
        ),
        migrations.AddField(
            model_name='text',
            name='reading',
            field=models.BooleanField(default=False, help_text='Reading this next now.'),
        ),
    ]
