# Generated by Django 3.0.3 on 2020-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='page',
            field=models.CharField(choices=[('BG', 'Blog'), ('SS', 'Stilus'), ('CT', 'Contact'), ('MC', 'Miscellaneous')], default='BG', help_text='The page this entry is for.', max_length=2),
        ),
    ]
