# Generated by Django 2.0.2 on 2018-03-19 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180319_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when this text came into my hands.', verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='text',
            name='read',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when this text was read.', verbose_name='created'),
        ),
    ]
