# Generated by Django 4.1.7 on 2023-03-19 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_entry_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_ancestors_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Ancestors count"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_children_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Children count"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_depth",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Depth",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_descendants_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Descendants count"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_index",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Index"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_level",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_order",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_priority",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ],
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="tn_siblings_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Siblings count"
            ),
        ),
        migrations.AlterField(
            model_name="static",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
