# Generated by Django 2.0.2 on 2018-03-20 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180319_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='text',
            name='type',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
