# Generated by Django 2.0.3 on 2018-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180320_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the pair.', max_length=200)),
                ('value', models.TextField(help_text='The value of the pair.')),
            ],
        ),
    ]
