# Generated by Django 2.0.3 on 2018-04-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_static'),
    ]

    operations = [
    ]
