# Generated by Django 2.0.2 on 2018-03-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='type',
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.ManyToManyField(blank=True, to='reading.Type'),
        ),
    ]
